import {classify,safeUrl,type Job} from './jobs';
import {plainText} from './public-feed';
export const INDIA_EMPLOYERS=[{id:'tata-consulting',name:'Tata Consulting Engineers',origin:'India',url:'https://careers.tataconsultingengineers.com',kind:'career'},{id:'tata-electronics',name:'Tata Electronics',origin:'India',url:'https://careers.tataelectronics.com',kind:'career'},{id:'bosch-india',name:'Bosch Group',origin:'International',url:'https://careers.smartrecruiters.com/BoschGroup/india',board:'BoschGroup',kind:'smart'},{id:'aecom-india',name:'AECOM India',origin:'International',url:'https://careers.smartrecruiters.com/AECOM2',board:'AECOM2',kind:'smart'},{id:'turner-india',name:'Turner & Townsend',origin:'International',url:'https://careers.smartrecruiters.com/TurnerTownsend',board:'TurnerTownsend',kind:'smart'},{id:'assystem-india',name:'Assystem India',origin:'International',url:'https://careers.smartrecruiters.com/ASSYSTEM',board:'ASSYSTEM',kind:'smart'}];
export function parseCareerPage(html:string,employer:typeof INDIA_EMPLOYERS[number],now=new Date().toISOString()):Job[]{if(html.length>1500000)throw Error('Page exceeds limit');const jobs:Job[]=[];const seen=new Set();for(const m of html.matchAll(/<li\b[^>]*class="job-tile\s[^>]*>([\s\S]*?)<\/li>/gi)){const chunk=m[1];const a=chunk.match(/<a\b[^>]*class="jobTitle-link[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const title=plainText(a[2]);const location=plainText(chunk.match(/<div\b[^>]*id="[^"]*section-location-value"[^>]*>([\s\S]*?)<\/div>/i)?.[1]||'');if(!/(?:^|,\s*)IN(?:,|$)|India/i.test(location))continue;const classification=classify(title,'');const url=safeUrl(new URL(a[1],employer.url).href);if(!classification||!url||seen.has(url))continue;seen.add(url);const id=url.match(/\/(\d+)\/$/)?.[1];jobs.push({id:`${employer.id}:${id}`,title,company:employer.name,location:location.replace(/\bIN\b/,'India'),...classification,type:'Not specified',workplace:'Not specified',experience:'Not specified',qualification:'Not specified',salary:null,postedAt:null,firstSeen:now,fetchedAt:now,confirmedAt:now,deadline:null,source:`${employer.name} careers`,sourceUrl:employer.url,url,description:'This opening is listed on the employer’s official careers page. Open the original listing for responsibilities, qualifications, experience requirements and application instructions.',country:'IN',language:'en',employerOrigin:employer.origin})}return jobs}
export function normalizeSmart(x:any,employer:typeof INDIA_EMPLOYERS[number],now=new Date().toISOString()):Job|null{if(x.location?.country?.toLowerCase()!=='in'||x.visibility&&x.visibility!=='PUBLIC'||x.language?.code!=='en')return null;const c=classify(String(x.name||''),'');if(!c)return null;const url=safeUrl(`https://jobs.smartrecruiters.com/${employer.board}/${x.id}`);if(!url||!/^\d+$/.test(String(x.id)))return null;const date=Date.parse(x.releasedDate);return {id:`${employer.id}:${x.id}`,title:x.name,company:employer.name,location:x.location.fullLocation||[x.location.city,x.location.region,'India'].filter(Boolean).join(', '),...c,type:x.typeOfEmployment?.label||'Not specified',workplace:x.location.remote===true?'Remote':x.location.hybrid===true?'Hybrid':x.location.remote===false?'On-site':'Not specified',experience:x.experienceLevel?.label||'Not specified',qualification:'Not specified',salary:null,postedAt:Number.isFinite(date)?new Date(date).toISOString():null,firstSeen:now,fetchedAt:now,confirmedAt:now,deadline:null,source:`${employer.name} · SmartRecruiters`,sourceUrl:employer.url,url,description:'This is a public employer posting for a position in India. Open the original listing for the complete English job description, eligibility and application instructions.',country:'IN',language:'en',employerOrigin:employer.origin,dateKind:'source'}}
async function textRequest(url:string){for(let n=0;n<2;n++){try{const r=await fetch(url,{signal:AbortSignal.timeout(20000),headers:{'User-Agent':'CorePathJobIndex/1.0','Accept':'text/html,application/json,text/plain'}});if(!r.ok)throw Error('Source unavailable');return await r.text()}catch{if(n===1)throw Error('Source unavailable');await new Promise(r=>setTimeout(r,1000))}}throw Error('Source unavailable')}
export async function fetchIndiaEmployer(e:typeof INDIA_EMPLOYERS[number]):Promise<Job[]>{const jobs:Job[]=[];if(e.kind==='career'){
 // Index factual title/location/link metadata only. Never access application/account/services paths.
 const robots=await textRequest(e.url+'/robots.txt');if(robots.split('\n').some(line=>/^Disallow:\s*(?:\/search\/?|\/)\s*$/i.test(line.trim())))throw Error('Search indexing not permitted');
 for(const q of ['civil','mechanical','electrical']){const html=await textRequest(`${e.url}/search/?q=${q}&startrow=0`);if(!/<html[^>]*lang="en/i.test(html))throw Error('English source required');jobs.push(...parseCareerPage(html,e))}
 }else{for(let page=0;page<2;page++){const data=JSON.parse(await textRequest(`https://api.smartrecruiters.com/v1/companies/${e.board}/postings?country=in&language=en&limit=100&offset=${page*100}`));if(!Array.isArray(data.content))throw Error('Invalid posting response');for(const x of data.content){const j=normalizeSmart(x,e);if(j)jobs.push(j)}if((page+1)*100>=data.totalFound)break}}
 return [...new Map(jobs.map(j=>[j.id,j])).values()]}
