import {database,runtime} from './server';
import {boardsFrom,fetchBoard} from './providers';
import {PUBLIC_FEEDS,fetchPublicFeed} from './public-feed';
import {INDIA_EMPLOYERS,fetchIndiaEmployer} from './india-feeds';

export async function ingestCatalog(){const db=database();const claim=await db.prepare('INSERT INTO ingestion_locks (id,expires) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET expires=excluded.expires WHERE ingestion_locks.expires < ?').bind('catalog',Date.now()+600000,Date.now()).run();if(!claim.meta.changes)return {status:'busy',results:[]};
 try{const latest:any=await db.prepare('SELECT fetched_at FROM provider_runs WHERE id=?').bind('catalog-cse-v2').first();if(latest&&Date.now()-Date.parse(latest.fetched_at)<60*60*1000)return {status:'recent',results:[]};const sources=[...INDIA_EMPLOYERS.map(e=>({id:e.id,fetch:()=>fetchIndiaEmployer(e)})),...PUBLIC_FEEDS.map(feed=>({id:feed.id,fetch:async()=>(await fetchPublicFeed(feed)).jobs})),...boardsFrom(runtime().JOB_BOARDS).map(board=>({id:`${board.provider}:${board.board}`,fetch:()=>fetchBoard(board)}))];const results=[];
 const existing=await db.prepare('SELECT id,payload FROM jobs LIMIT 2000').all();const originals=new Map(existing.results.map((r:any)=>[r.id,JSON.parse(r.payload).firstSeen]));
 for(const s of sources){let count=0,status='failed';try{const jobs=await s.fetch();const statements=jobs.map(j=>{const key=j.id;if(originals.has(key))j.firstSeen=originals.get(key) as string;return db.prepare('INSERT INTO jobs (id,dedup,payload,branch,posted_at,fetched_at,deadline) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET dedup=excluded.dedup,branch=excluded.branch,payload=excluded.payload,fetched_at=excluded.fetched_at,posted_at=excluded.posted_at,deadline=excluded.deadline').bind(j.id,key,JSON.stringify(j),j.branch,j.postedAt,j.fetchedAt,j.deadline)});for(let offset=0;offset<statements.length;offset+=100)await db.batch(statements.slice(offset,offset+100));count=jobs.length;status='ok'}catch{status='failed'}await db.prepare('INSERT INTO provider_runs (id,status,fetched_at,count) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,fetched_at=excluded.fetched_at,count=excluded.count').bind(s.id,status,new Date().toISOString(),count).run();results.push({provider:s.id,status,count})}
 if(results.some(r=>r.status==='ok'))await db.prepare('INSERT INTO provider_runs (id,status,fetched_at,count) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,fetched_at=excluded.fetched_at,count=excluded.count').bind('catalog-cse-v2','ok',new Date().toISOString(),results.reduce((n,r)=>n+r.count,0)).run();
 // Never call missing jobs closed. Exclude unconfirmed older cache records from search instead.
 await db.prepare('DELETE FROM jobs WHERE fetched_at < ?').bind(new Date(Date.now()-7*86400000).toISOString()).run();return {status:results.some(r=>r.status==='ok')?'updated':'failed',results};
 }finally{await db.prepare('DELETE FROM ingestion_locks WHERE id=?').bind('catalog').run()}}
