import {classify,safeUrl,type Job} from './jobs';
export const PUBLIC_FEEDS=[{id:'arbeitnow-uk',name:'Arbeitnow · United Kingdom',url:'https://www.arbeitnow.co.uk/api/job-board-api',country:'United Kingdom',credit:'https://www.arbeitnow.co.uk'}];
export function plainText(input:string){return input.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<\s*(?:br|\/p|\/li|\/h[1-6])\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#(?:0*39|x27);/gi,"'").replace(/&nbsp;/g,' ').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).slice(0,18000).trim()}
export function normalizePublicJob(x:any,feed:typeof PUBLIC_FEEDS[number],now=new Date().toISOString()):Job|null{
 if(typeof x.title!=='string'||typeof x.company_name!=='string'||typeof x.slug!=='string')return null;
 const description=plainText(String(x.description||''));const c=classify(x.title,'');const url=safeUrl(x.url);if(!c||!url)return null;
 const stamp=Number(x.created_at);const postedAt=Number.isFinite(stamp)&&stamp>0&&stamp*1000<=Date.now()+86400000?new Date(stamp*1000).toISOString():null;
 const types=Array.isArray(x.job_types)?x.job_types.join(' '):'';const opportunity=/intern|praktik/i.test(types)?'Internship':/apprentice|ausbildung/i.test(types)?'Apprenticeship':/contract|freelance/i.test(types)?'Contract':/full.time|vollzeit/i.test(types)?'Full-time':types||'Not specified';
 return {id:`${feed.id}:${x.slug}`,title:x.title,company:x.company_name,location:`${x.location||'Location unavailable'}, ${feed.country}`,...c,type:opportunity,workplace:x.remote===true?'Remote':x.remote===false?'On-site':'Not specified',experience:'Not specified',qualification:'Not specified',salary:null,postedAt,firstSeen:now,fetchedAt:now,confirmedAt:now,deadline:null,source:feed.name,url,description,dateKind:'source',sourceUrl:feed.credit,country:'GB',language:'en',employerOrigin:'International'};
}
export async function fetchPublicFeed(feed:typeof PUBLIC_FEEDS[number]){const jobs:Job[]=[];let pages=0;for(let page=1;page<=3;page++){let data:any;for(let attempt=0;attempt<3;attempt++){try{const response=await fetch(`${feed.url}?page=${page}`,{signal:AbortSignal.timeout(15000),headers:{Accept:'application/json'}});if(!response.ok){if(response.status!==429&&response.status<500)throw new Error('Provider rejected request');throw new Error('Provider temporarily unavailable')}data=await response.json();break}catch{if(attempt===2)throw new Error('Public feed unavailable');await new Promise(r=>setTimeout(r,500*2**attempt))}}if(!Array.isArray(data?.data))throw new Error('Invalid feed response');for(const item of data.data.slice(0,400)){const j=normalizePublicJob(item,feed);if(j)jobs.push(j)}pages++;if(!data.links?.next)break}return {jobs,pages}}
